// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vaovpdtztrsxxxrvtfus.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhb3ZwZHR6dHJzeHh4cnZ0ZnVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MTM5NDksImV4cCI6MjA2MDE4OTk0OX0.HW06_dFRkiPVyprEFyiNRt1Mz-jN8Qi2DS4XsGDqS0w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);