// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqoyvamufjlhrayfumrt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpxb3l2YW11ZmpsaHJheWZ1bXJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NDUxMDcsImV4cCI6MjA2MDEyMTEwN30.t9NfB0dmk5Msph4pvab8cy3BcbhyROHFtyQZwx1Y2mE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);